### ISSUE TITLE
Does this code work? Cant proceed after installation

### ISSUE THREAD

**Issue by connecteev** [pktharindu/nuxt-laravel-passport-example#1]
@pktharindu thanks for the repo...but doesnt work. I installed laravel and nuxt and they're both running, but not sure how to proceed.

This is what I see at localhost:3000/login:
https://prnt.sc/ovvd2m

In laravel I only see these api routes:
```
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

Route::group(['middleware' => 'auth:api'], function () {
    Route::get('auth/me', 'AuthController@local');
    Route::get('oauth/me', 'AuthController@oauth');
});

```

**Comment by pktharindu** [comment]
It is using Laravel passport for authentication. Passport routes are registered under `AuthServiceProvider`. So you won't see them in api routes.
Try using the `UserFactory` to add some users to the database and you should be able to log in as any one of them.
