### ISSUE TITLE
Problem with verification account by email

### ISSUE THREAD

**Issue by pawelwtorek** [pktharindu/nuxt-laravel-passport-example#12]
Hi,

I installed app correctly and it was all working. After few days i have problem with email verification. When i click in email link:
http://localhost:3000/verify-email/31/ad18740a97c0721038f80420d8f0550f41d9d28e?expires=1611341038&signature=1df002269cd21769474935683315bdef223f4bb50b380e2a06a6d2cb7eeb1a87

then it go to browser and open login page but without information that account is confirmed and i cant login also.
What is the problem? How to find reason? I installed app few times and problem still exist (also reinstall composer and nodejs)

I added in RedirectIfAuthenticated log requests:
Log::channel('daily')->info(get_class($this) . " - Handle an incoming request: " . $request);

but when i open link with GET it dont detect any request so app cant verify my email.

regards

===============================
edit:
becouse i made some changes in app few times i once again generated:
php artisan key:generate
php artisan passport:install

and it works now!
could that be the reason ?

But btw question:
when i clicked in email to confirm link i go to login page and i dont have information that email is confirmed. But i can login correctly and after it i have info that i am not confirmed and i have to go to email clicked again the same link and after it i have info that now im confirmed.
Is that logic is correct or is it some bug ?

**Comment by pktharindu** [comment]
Hey,

So, to verify the email, the user needs to be logged in first. That is just how default email verification works in Laravel.
The reason could be because someone could verify another user's email address if they somehow gain access to the verification email.

I personally find it hardly a risk at all.
So in most of my projects, I usually remove authentication middleware from the `VerificationController` and override the `verify` method in the `VerifiesEmails` trait.

Something like this should do the trick:

```php
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\Events\Verified;
use Illuminate\Foundation\Auth\VerifiesEmails;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class VerificationController extends Controller
{
    use VerifiesEmails;

    protected $redirectTo = RouteServiceProvider::HOME;

    public function __construct()
    {
        $this->middleware('auth:api')->except('verify');
        $this->middleware('signed')->only('verify');
        $this->middleware('throttle:6,1')->only('verify', 'resend');
    }

    public function verify(Request $request)
    {
        $user = User::find($request->route('id'));

        if (! hash_equals((string) $request->route('id'), (string) $user->getKey())) {
            throw new AuthorizationException;
        }

        if (! hash_equals((string) $request->route('hash'), sha1($user->getEmailForVerification()))) {
            throw new AuthorizationException;
        }

        if ($user->hasVerifiedEmail()) {
            return $request->wantsJson()
                ? new JsonResponse([], 204)
                : redirect($this->redirectPath());
        }

        if ($user->markEmailAsVerified()) {
            event(new Verified($user));
        }

        if ($response = $this->verified($request)) {
            return $response;
        }

        return $request->wantsJson()
            ? new JsonResponse([], 204)
            : redirect($this->redirectPath())->with('verified', true);
    }
}
```

I think it's still secure, as the request is signed and verified.
