### ISSUE TITLE
dont work login

### ISSUE THREAD

**Issue by mahmood-moosavian** [pktharindu/nuxt-laravel-passport-example#14]
when do login in response return me

Request URL: http://localhost:3000/_auth/laravelPassportPassword/token
Request Method: POST
Status Code: 400 Bad Request

**Comment by pktharindu** [comment]
Have you correctly filled out the `.env` file on the Nuxt site?
If so, try making a request to `/oauth/token` using an API client like Passport, to make sure there aren't any issues on the Laravel end.

**Comment by mahmood-moosavian** [comment]
I dont knew that  Client ID and  Client secret put into .env nuxt.
I did it, and it so work, excuse me for this mistake.

**Comment by pktharindu** [comment]
No problem 🙂
