### ISSUE TITLE
I can not login

### ISSUE THREAD

**Issue by sillexo** [pktharindu/nuxt-laravel-passport-example#17]
Hello! I can't login after registration
**http://localhost:3000/_auth/laravelPassportPassword/token**
return Status Code: 401 Unauthorized
```
error: "invalid_client"
error_description: "Client authentication failed"
message: "Client authentication failed"
```
My .env
`API_URL="http://localhost:8000"
PASSPORT_CLIENT_ID=92e88ed3-ef90-4d53-9e3a-2e125cddbb87
PASSPORT_CLIENT_SECRET=0Wod00v13GaKgt0oKLgRQNWft0Nm58qSV8tk5dqB`

**Comment by pktharindu** [comment]
Hi 👋🏻

Have you filled out the `.env` file on the Nuxt site?

**Comment by sillexo** [comment]
Yes, here are its contents
`API_URL="http://localhost:8000"
PASSPORT_CLIENT_ID=92e88ed3-ef90-4d53-9e3a-2e125cddbb87
PASSPORT_CLIENT_SECRET=0Wod00v13GaKgt0oKLgRQNWft0Nm58qSV8tk5dqB`

**Comment by pktharindu** [comment]
Can you try making a request to `/oauth/token` using an API client like Passport, to make sure there aren't any issues on the Laravel end.

**Comment by sillexo** [comment]
![image](https://user-images.githubusercontent.com/1457495/110459427-c9bb5000-80ee-11eb-8be4-676f27b6e80e.png)

**Comment by pktharindu** [comment]
Actually, we are trying to check the Laravel side of things. So, the domain should be `http://localhost:8000`. Also, the `client_id` and the `client_secret`  should reflect your Passport credentials.

**Comment by sillexo** [comment]
Sorry )
![image](https://user-images.githubusercontent.com/1457495/110460845-8d88ef00-80f0-11eb-86d6-65c149a2665a.png)

**Comment by pktharindu** [comment]
Great! So the server seems to be working just fine.

If you put the credentials to the Nuxt `.env`, it should work. Or are you still running into the same issue?

**Comment by sillexo** [comment]
Thank you very much, I did it!

**Comment by pktharindu** [comment]
Glad I could help! 😊
