### ISSUE TITLE
Nuxt.js part not working with Laravel 7.3 Passport because of CORS, any update ?

### ISSUE THREAD

**Issue by devondahon** [pktharindu/nuxt-laravel-passport-example#3]
The last version of Laravel Passport comes with CORS, so the Nuxt.js part doesn't work anymore with this version. Would update the code to fit this new release ?

**Comment by pktharindu** [comment]
This is actually an old repo. I've been meaning to update but didn't really get around to doing it. But at some point, I will. Feel free to submit a PR if possible.
