### ISSUE TITLE
How to verify login using username & password instead of email & password?

### ISSUE THREAD

**Issue by jasper4ni** [pktharindu/nuxt-laravel-passport-example#33]
How to verify login using username & password instead of email & password?

Hi, I'm using this repo as my reference to build my app, but I wonder how can I verify the login by username and password.
Thanks in advance!

**Comment by pktharindu** [comment]
If you look **[here](https://github.com/laravel/passport/blob/7a026acac7576224474f9f51b3b04d8b4541c0e7/src/Bridge/UserRepository.php#L52)**, you will see it first looks for a `findForPassport` method on the auth model. So if you implement your own `findForPassport` method on the user model, you can customize it to use the username field instead.

You can add something like this to your `User` model:
```php
public function findForPassport($identifier) {
    return $this->where('username', $identifier)->first();
}
```
