### ISSUE TITLE
How do I implement passport scope function to Nuxt auth?

### ISSUE THREAD

**Issue by jasper4ni** [pktharindu/nuxt-laravel-passport-example#34]
How do I implement scope function to Nuxt auth?

I've checked the article that I can found on google, but there's no one giving the accurate method.
please help me with this!
Thanks in advance!

**Comment by pktharindu** [comment]
In Nuxt auth the [scopeKey is `scope` by default](https://auth.nuxtjs.org/api/options#scopekey).  You can check if the user has a [specific scope](https://auth.nuxtjs.org/api/auth#hasscopescopename):

```js
this.$auth.hasScope('admin')
```

Here is a tutorial on how to configure the Laravel app: https://www.codecheef.org/article/laravel-passport-scope-tutorial-api-permissions-using-passport-scope.

**Comment by jasper4ni** [comment]
Here is my login function define in laravel, 
```php
public function login(Request $request) {
	$request->validate([
		'username' => 'required',
		'password' => 'required',
	]);

	$credentials = $request->only(['username', 'password']);
    
	if (Auth::attempt($credentials)) {
		$user = Auth::user();
		$role = Auth::user()->roles->first()->name;
		if($role){
			switch ($role) {
				case 'admin':
					$success['token'] = $user->createToken('NuxtApp', ['admin'])->accessToken;
					break;
				case 'user':
					$success['token'] = $user->createToken('NuxtApp', ['user'])->accessToken;
					break;
				default:
					break;
			}
		}
		return response()->json(['success' => $success], 200);
	}
	else {
		return response()->json(['error' => 'Unauthorized'], 401);
	}
}
```
The api route
```php
Route::prefix('auth')->group(function () {
	Route::post('login', 'Auth\PassportController@login');
	Route::post('logout', 'Auth\PassportController@logout');
	Route::middleware('auth:api')->get('user', 'Auth\PassportController@user');
});
```
And the nuxt.config.js stratergy
```js
strategies: {
      laravelPassportPasswordGrant: {
        name: 'laravelPassportPassword',
        provider: 'laravel/passport',
        url: process.env.API_URL,
        endpoints: {
          login: { 
            url: '/api/auth/login', 
            method: 'post', 
          },
          logout: '/api/auth/logout',
          user: {
            url: '/api/auth/user',
          },
        },
        clientId: process.env.PASSPORT_CLIENT_ID,
        clientSecret: process.env.PASSPORT_CLIENT_SECRET,
        grantType: 'password',
      },
    },
```
In login page I do
```js
await this.$auth
loginWith('laravelPassportPassword', { data: this.form })
  then(() => {
  this.$router.push('/');
})
.catch((e) => {
  this.$toast.global.error({ message: this.$t('unauthorized')})
})
```

But the request is still sent to http://localhost:3000/_auth/laravelPassportPassword/token

How do I make the token request to login controller?
Or how to return scope with the default token request?

**Comment by jasper4ni** [comment]
> In Nuxt auth the [scopeKey is `scope` by default](https://auth.nuxtjs.org/api/options#scopekey). You can check if the user has a [specific scope](https://auth.nuxtjs.org/api/auth#hasscopescopename):
> 
> ```js
> this.$auth.hasScope('admin')
> ```
> 
> Here is a tutorial on how to configure the Laravel app: https://www.codecheef.org/article/laravel-passport-scope-tutorial-api-permissions-using-passport-scope.

Sir, please help with the question, I really need your help, thanks!

**Comment by pktharindu** [comment]
There is no login route in Passport. Instead, the issue token is functionality is there in `/oauth/token` route. You can overwrite it if you need. But as for the scoping, it should be returned on the `user` route instead, not issue token.

If you are just looking for a way to do access control, take a look at https://github.com/spatie/laravel-permission.

**Comment by jasper4ni** [comment]
oh, okay. I've try to pass the scope on user route, with two method
**1st**
u can see the createToken()
but this is useless, I cant detect any scope on my frontend and backend
```php
public function user()
{
    $user = Auth::user();
    $userInfo = [
        'id' => $user->id,
        'username' => $user->username,
        'name' => $user->name,
        'email' => $user->email,
        'role' => $user->roles->first()->id,
        'role_name' => $user->roles->first()->name,
    ];
    $role = $user->roles->first()->name;
    if($role) {
        switch ($role) {
            case 'admin':
                $userInfo['rolePath'] = 'admin';
                $user->createToken('NuxtApp', ['admin'])->accessToken;
                break;
            case 'user':
                $userInfo['rolePath'] = 'account';
                $user->createToken('NuxtApp', ['user'])->accessToken;
                break;
            default:
                break;
        }
    }
    return $userInfo;
}
```

**2nd**
I just pass the scope as response back to nuxt, but in this method, whatever I call `$auth.hasScope('admin')`, or `$auth.hasScope('user')`, it's always return true
```php
public function user()
{
    $user = Auth::user();
    $userInfo = [
        'id' => $user->id,
        'username' => $user->username,
        'name' => $user->name,
        'email' => $user->email,
        'role' => $user->roles->first()->id,
        'role_name' => $user->roles->first()->name,
    ];
    $role = $user->roles->first()->name;
    if($role) {
        switch ($role) {
            case 'admin':
                $userInfo['rolePath'] = 'admin';
                $user['scope'] = 'admin';
                break;
            case 'user':
                $userInfo['rolePath'] = 'account';
                $user['scope'] = 'user';
                break;
            default:
                break;
        }
    }
    return $userInfo;
}
```

What's the proper method to pass scope in user route?

**Comment by pktharindu** [comment]
If you are already using role-based permissions, why not just use that for checking authorization? You could return an array of permissions along with the user object and use that to handle things on the frontend.

**Comment by jasper4ni** [comment]
I wanna protect the API route from malicious connect, and the scope function has more concise way to do this job.
So what's the suitable method to pass the scope nice and well?

**Comment by pktharindu** [comment]
I think you can use the `Passport::scopes()` method to fetch the scopes and then pass it with the user object. But I haven't done this myself, so I can't be sure. I find role-based access control to be a much more robust solution.
