### ISSUE TITLE
Can use granttype: 'client_credentials'   authorized to access API information ?

### ISSUE THREAD

**Issue by MarkHe2022** [pktharindu/nuxt-laravel-passport-example#47]
Now there is a requirement that the API is authorized to call the website。

API authorized siteA、siteB....

thankyou.

**Comment by pktharindu** [comment]
This example uses the password grant type with a focus on user authentication. The client credentials grant is usually used for machine-to-machine authentication, for example, running a scheduled job over an API. It is not supported by the Nuxt auth plugin out of the box. But technically you might be able to [extend the auth plugin](https://auth.nuxtjs.org/recipes/extend) to facilitate this. I'm not sure the client credentials grant type is the right choice on the account of Nuxt being a frontend application. But of course I can't say that for sure without knowing what the use-case is.
