### ISSUE TITLE
There is no endpoint for login route

### ISSUE THREAD

**Issue by amitleuva1987** [pktharindu/nuxt-laravel-passport-example#55]
Below is the auth configuration in nuxt.config.js

```
auth: {
    redirect: {
      home: '/profile',
    },
    strategies: {
      laravelPassportPasswordGrant: {
        name: 'laravelPassportPassword',
        provider: 'laravel/passport',
        url: '/backend',
        endpoints: {
          logout: '/api/v1/logout',
          user: {
            url: '/api/v1/user',
          },
        },
        clientId: process.env.PASSPORT_CLIENT_ID,
        clientSecret: process.env.PASSPORT_CLIENT_SECRET,
        grantType: 'password',
      },
    },
  },

```

I don't see any endpoint for login route, how does login work?

**Comment by pktharindu** [comment]
The Nuxt auth module has that by default. [Docs here.](https://dev.auth.nuxtjs.org/providers/laravel-passport)

**Comment by amitleuva1987** [comment]
@pktharindu , Ofcourse, Nuxt has the the login route within the auth module. But, I also don't see login route defined in the Laravel 'api.php'. How does front end find the login route?

**Comment by pktharindu** [comment]
It is coming from the `Passport::routes()` which is defined here: https://github.com/pktharindu/nuxt-laravel-passport-example/blob/a42df3a72c54c9e0a7289eaacb5fb44e337c0882/laravel/app/Providers/AuthServiceProvider.php#L29-L34
